ac_add_options --disable-crashreporter
ac_add_options --disable-webrtc
# ac_add_options --disable-webm
# ac_add_options --disable-opus
ac_add_options --disable-webspeech
ac_add_options --disable-webgl
ac_add_options --disable-gstreamer
ac_add_options --disable-ffmpeg
ac_add_options --disable-fmp4
# ac_add_options --disable-wave
ac_add_options --disable-gamepad
ac_add_options --disable-eme

ac_add_options --disable-printing
ac_add_options --disable-embedding-tests

ac_add_options --with-system-icu
ac_add_options --with-system-jpeg
ac_add_options --with-system-zlib
ac_add_options --with-system-bz2
ac_add_options --with-system-png
ac_add_options --with-system-libevent
ac_add_options --with-system-libvpx
