#!/bin/bash

#
# Script template - a copyable base script for making quick ~/bin/ stuff
#   Put synopsis here -- find all occurrances of `XX` for bits to tweak
#

set -euo pipefail
# shellcheck source=./lib/util.sh
. ~/bin/lib/util.sh

## Args and usage

#                                            keep help text below 81st column ->|
n_init_args_and_usage 'my_scriptXX' 'option,help,XX' 'ohXX' "$@" <<'EOF'
Usage: my_scriptXX [options] [--] arg arg2 XX
  Help text here XX

--option / -o  Help text for option XX
--help / -h    Show this help
EOF

# --help
[[ -n $(get_merged_option help h) ]] && n_usage_and_exit

# Fetch args
eval args="($(get_args))"

option=$(get_merged_option option o) # XX
