## which filter mode to use when atuin is invoked from a shell up-key binding
## the accepted values are identical to those of "filter_mode"
## leave unspecified to use same mode set in "filter_mode"
filter_mode_shell_up_key_binding = "session"

## which style to use
## possible values: auto, full, compact
style = "compact"

## the maximum number of lines the interface should take up
## set it to 0 to always go full screen
inline_height = 20


## Defaults to true. If enabled, upon hitting enter Atuin will immediately execute the command. Press tab to return to the shell and edit.
# This applies for new installs. Old installs will keep the old behaviour unless configured otherwise.
enter_accept = false

# Makes it good maybe?
search_mode = "daemon-fuzzy"

[daemon]
enabled = true
autostart = true

# By default doesn't show stuff from e.g. bash? Because?
[search]
shells = "all"

